LIST_TASKS          = "/tasks/task_list"
CREATE_TASK         = "/tasks/create_task"
UPDATE_TASK         = "/tasks/update_task"
DELETE_TASK         = "/tasks/delete_task"
ORDER_TASKS         = "/tasks/order_task"
REGISTER_USER       = "/tasks/register_user"
VALIDATE_OTP        = "/tasks/verify_otp"
GENERATE_OTP        = "/tasks/generate_otp"